#!/bin/bash
#
# Launch one of the example applications.
#
# This is a simple shortcut script for development purposes. See the service
# directory for scripts suitable for running this application as a service.
#
# Usage: launch-application {application}
#

if [ "$#" -ne 1 ]; then
  echo "Usage: launch-application {application}"
  exit 1
fi

export NODE_PATH=$NODE_PATH:/home/node/local/node/lib/node_modules;
export NODE_HOME=/home/node/local/node

if [ -f $NODE_HOME/lib/node_modules/thywill/applications/$1/service/start.js ]; then
  $NODE_HOME/bin/node $NODE_HOME/lib/node_modules/thywill/applications/$1/service/start.js &
else 
  echo "Application $1 does not exist or has no service/start.js file."
  exit 1
fi