#!/bin/bash
#
# Launch this example application. 
#
# This is a simple shortcut script for development purposes. See the service
# directory for scripts suitable for running this application as a service.

export NODE_PATH=$NODE_PATH:/home/node/local/node/lib/node_modules;
export NODE_HOME=/home/node/local/node
export APPLICATION=echo

$NODE_HOME/bin/node $NODE_HOME/lib/node_modules/thywill/applications/$APPLICATION/service/start.js &